### ISSUE TITLE
[建议]汉化A营一些拓展模块

### ISSUE THREAD

**Issue by ch-LyricEpic** [a49594a/a-world-issues#10]
例如Community 模块以及Puzzles模块还有新开发的Canvas模块
建议Canvas和Python的Turtle同时可以支持.

汇总:需要汉化的模块:Community.Canvas.Kinect.MakeyMakey.LEGO BOOST.Force and Acceleration 模块

**Comment by ch-luckylai** [comment]
已经有此建议
