### ISSUE TITLE
[bug]禁止评论后依然可以通过接口发送评论

### ISSUE THREAD

**Issue by sparrowhe** [a49594a/a-world-issues#102]
如题，使用道具封闭评论区后，依然可以通过修改控件属性或者直接调用api发送评论

**Comment by zhangyul** [comment]
请问你是有看到谁绕过限制通过api直接访问的么？这样算是违规的，可以直接举报到举报中心

**Comment by sparrowhe** [comment]
> 请问你是有看到谁绕过限制通过api直接访问的么？这样算是违规的，可以直接举报到举报中心

不是说谁绕过限制了，只是说有这个bug

**Comment by zhangyul** [comment]
> > 请问你是有看到谁绕过限制通过api直接访问的么？这样算是违规的，可以直接举报到举报中心
> 
> 不是说谁绕过限制了，只是说有这个bug

明白，不过这不能算是bug，一般用户都是通过正常手段访问的，为了提高处理效率，除了安全性的接口，不是所有接口都会限制框死的。
