### ISSUE TITLE
[bug]在课程中留言对应老师的主页会显示不完整动态

### ISSUE THREAD

**Issue by jimowutong888** [a49594a/a-world-issues#107]
## 预期行为

  **应该显示: XXX 在 课程 中 留言了**

## 实际行为

  **实际显示: XXX 在**

## 操作步骤

  **在任意课程中留言**

![](https://asset.mozhua.org:444/Media?name=26001147FE167733D04B9182680C1BE9.png)

**Comment by zhangyul** [comment]
![image](https://user-images.githubusercontent.com/12007267/80181022-9b4b9800-8636-11ea-85ae-5ea526352e0d.png)
感谢反馈已修复
