### ISSUE TITLE
[bug]Scratch-blocks在作品简介的显示问题的bug

### ISSUE THREAD

**Issue by Doushabao233** [a49594a/a-world-issues#112]
## 预期行为

在作品简介里使用Scratch-blocks插入一个字非常长的积木（例如：你好————————————————————————————————），没有问题

## 实际行为

积木直接跑出了屏幕：

![image](https://user-images.githubusercontent.com/64591791/80710514-7321d480-8b21-11ea-89bc-209a1223d5cb.png)

## 操作步骤

在作品简介里输入一个名字很长的Scratch-blocks

## 系统（非必要）

无

**Comment by zhangyul** [comment]
目前是出滚动条的，因为时间有点久我不太确定是否和你当时反馈的是一样的
