### ISSUE TITLE
[bug]舞台上的旗子不消失

### ISSUE THREAD

**Issue by tzTZtzTZqwq** [a49594a/a-world-issues#119]
## 预期行为

 加载完成后点旗子之后舞台上原有的开始旗子会消失（都是开始键

## 实际行为

 点舞台上方旗子之后舞台上原有的开始旗子没有消失
![QQ截图20200510135945](https://user-images.githubusercontent.com/65105227/81491976-8a518680-92c6-11ea-8f59-5d67522c449f.png)
作品在这已经开始了但是旗子没消失

## 操作步骤

把浏览器拉到半屏时进入作品

## 系统（非必要）

chome，电脑

**Comment by Flancok** [comment]
duplicate #8
