### ISSUE TITLE
[建议]关于A营的一些建议

### ISSUE THREAD

**Issue by ch-LyricEpic** [a49594a/a-world-issues#12]
1.希望可以增加Python爬虫扩展。
2.可以增加基于Griffpatch制作的SB32HTM的魔抓SB文件转换为HTML,现有的SB3格式无法被Scratch Desktop打开；
3.个人主页挂件能否将上限调高一些

**Comment by a49594a** [comment]
爬虫非常容易被滥用，暂时不会考虑增加。如果有兴趣可以自行学习代码式编程语言；
sb转html可以使用第3方工具，不会被官方支持；
头像挂件上限增加，将来会慎重考虑

**Comment by ch-LyricEpic** [comment]
为何慎重考虑第三?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "john"<notifications@github.com&gt;; 
发送时间: 2020年2月13日(星期四) 中午11:06
收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 
抄送: "叶州 普通账户"<177264839@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [a49594a/a-world-issues] [建议]关于A营的一些建议 (#12)




爬虫非常容易被滥用，暂时不会考虑增加。如果有兴趣可以自行学习代码式编程语言；
 sb转html可以使用第3方工具，不会被官方支持；
 头像挂件上限增加，将来会慎重考虑
