### ISSUE TITLE
[bug]声望值增加过少

### ISSUE THREAD

**Issue by Epaf3713** [a49594a/a-world-issues#120]
## 预期行为

  **投票、有效举报应当增加声望值**

## 实际行为

  **我投出了8张初精票，并提供过不少有效举报，但是已经超过一周，我的声望值只增加了2**

## 操作步骤

  **投票+举报，然后没有增加声望**

## 系统（非必要）

  **Windows64位，Google浏览器**

**Comment by zhangyul** [comment]
否决票是不加声望的，举报如果不是“采纳”也是不加的

**Comment by Epaf3713** [comment]
就是举报采纳了，投票不增加我知道是怎么回事，但是举报应该是增加的

**Comment by Flancok** [comment]
> 就是举报采纳了，投票不增加我知道是怎么回事，但是举报应该是增加的

投票需要作品审核通过且没有被否决才会增加声望
