### ISSUE TITLE
[bug]某些人可以看到未发布的内容

### ISSUE THREAD

**Issue by Epaf3713** [a49594a/a-world-issues#121]
## 预期行为

  **本来应该没发布的部分不会被别人看到**

## 实际行为

  **然而余老师在看我的一个作品时，看到了还未发布的部分，当时正在大更，bug一堆，所以我错过了一个机会很不爽**

## 操作步骤

  **余老师可以看到**

**Comment by zhangyul** [comment]
为了便于管理，我们系统的超级管理员是可以看到未发布的作品的。
