### ISSUE TITLE
[bug]自定义模块无法删除

### ISSUE THREAD

**Issue by Epaf3713** [a49594a/a-world-issues#128]
## 预期行为

  **如果有运用这个模块，那么不能删除，否则可以删除**

## 实际行为

  **已经确认没有使用一个模块，但是依然显示不能删除**

## 操作步骤

  **创建了一个模块，没有使用它，但是删不掉**

**Comment by YuzhenQin** [comment]
这边建议您去[这里](http://github.com/llk/scratch-gui)提交issue呢
