### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ch-LyricEpic** [a49594a/a-world-issues#14]
1.魔抓下载的SB3文件无法在ScratchDesktop中打开以及无法被HTMLifer转换为HTML,希望修复(貌似是因为拓展块的原因,能否在下载文件时检测作品中使用的拓展块并且同时下载该拓展块的ScratchDesktop配置文件?)
2.给别人点赞会将点赞人数+4

**Comment by Flancok** [comment]
请勿重复提交

**Comment by ch-luckylai** [comment]
2.点赞数量和等级相关
