### ISSUE TITLE
想要加z轴

### ISSUE THREAD

**Issue by Plumodd** [a49594a/a-world-issues#18]
详细：就是` 第三维坐标`（即Z轴）
虽然可以用角色大小做到
但是如果在里面加一个`视角`呢？（视角的位置，用xyz坐标设置）
/手动滑稽
/这样就可以弄贴图方块啦qwq

**Comment by Flancok** [comment]
短期内不太可能实现，如果加了就和原版scratch不兼容了。

**Comment by Plumodd** [comment]
没事，我乱说的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "frank-782"<notifications@github.com&gt;; 
发送时间: 2020年2月13日(星期四) 下午2:32
收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 
抄送: "Plum odd"<1852737632@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [a49594a/a-world-issues] 想要加z轴 (#18)




短期内不太可能实现，如果加了就和原版scratch不兼容了。
