### ISSUE TITLE
未分享作品显示程序出错

### ISSUE THREAD

**Issue by frank-782** [a49594a/a-world-issues#2]
未分享的作品出错而不是显示作品未发布

**Comment by a49594a** [comment]
是直接进入editor时会出错吗？

**Comment by Flancok** [comment]
> 是直接进入editor时会出错吗？

作品页 比如[Link](https://www.aerfaying.com/Projects/360721)

**Comment by ch-luckylai** [comment]
补充一下，可能是因为js找不到creator，所以就出现错误

**Comment by a49594a** [comment]
已经修复
