### ISSUE TITLE
[建议]可调整的帧率速度模块

### ISSUE THREAD

**Issue by Steve-xmh** [a49594a/a-world-issues#20]
添加一个`将执行帧率设定为 (30) 帧`的模块（功能详情就不用说了吧）

**Comment by ch-luckylai** [comment]
估计不会出现，请左转到cc

**Comment by Steve-xmh** [comment]
> 估计不会出现，请左转到cc

我觉得不难做啊，得有个令人信服的技术理由a。而且帧率是可控的，默认值是30，这样不会影响到原来的工程的正常运行，高帧率已是游戏玩家的需求之一了，为了更好的游戏体验和开发效果我觉得很有用处。

（如果 A 营的 scratch-vm 源码库是实时更新的话，我也可以 fork 一份发个 pr，就看你们愿不愿意了）
