### ISSUE TITLE
[建议]添加普通画笔模块在舞台上打印的层数调整

### ISSUE THREAD

**Issue by aaa123206** [a49594a/a-world-issues#21]
画笔打印时会固定打印在背景层上，会造成许多不方便的事情。比如做OS时想要在某个角色窗口内打印一些信息，则无法进行打印在角色上的操作，造成不便。

**Comment by aaa123206** [comment]
建议发布:清潇
A营账号:1111111

**Comment by ch-luckylai** [comment]
实现比较困难

**Comment by a49594a** [comment]
不会增加该功能，容易与现有角色层数控制机制产生冲突。
