### ISSUE TITLE
2.0转3.0后未发布的无法进入创作页的bug（可以不管）

### ISSUE THREAD

**Issue by F-park** [a49594a/a-world-issues#27]
# 模板：

- bug

## 预期行为

![image](https://user-images.githubusercontent.com/52167622/74581635-701c4b00-4fec-11ea-8230-2d94f466a193.png)

## 实际行为

![image](https://user-images.githubusercontent.com/52167622/74581631-52e77c80-4fec-11ea-86a8-00db71121413.png)

## 操作步骤

1.点开一个自己的2.0作品的展示页
2.点击转到3.0设计页按钮
3.保存作品
4.回到我的作品，点开该作品的设计页，就会出现如上bug

## 系统（非必要）

windows10

- 建议

无

**Comment by F-park** [comment]
前提是不要发布，应该是检测作品版本的问题

**Comment by Flancok** [comment]
应该不算bug，因为我的作品的页面没有刷新（所以还是认为此作品是2.0的）刷新一下我的作品页面有没有这个问题？

**Comment by Flancok** [comment]
所以只能算特性
![9NCW6CXI~D5%}U46W%_7WW3](https://user-images.githubusercontent.com/46376077/74581727-95f61f80-4fed-11ea-85d3-4c5c7cdfb115.png)

**Comment by F-park** [comment]
也许，没试过

**Comment by F-park** [comment]
不过有个/，不是特性吧

**Comment by ch-luckylai** [comment]
2.0转3.0之后原来的界面是不可以被访问的，不属于bug
