### ISSUE TITLE
[关于A营邀请码机制问题建议]

### ISSUE THREAD

**Issue by ch-LyricEpic** [a49594a/a-world-issues#28]
建议每个用户绑定手机号,每个手机号仅可绑定一个账号.这样不会出现一个用户通过刷小号来获取感染力勋章。

**Comment by Flancok** [comment]
守护煮以前说的：这个因为有一些老师邀请学生注册的情况，所以不能这样限制（如果有更好的建议可以提出）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LyricEpic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午2:05
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[a49594a/a-world-issues] [关于A营邀请码机制问题建议] (#28)




建议每个用户绑定手机号,每个手机号仅可绑定一个账号.这样不会出现一个用户通过刷小号来获取感染力勋章。

**Comment by ch-LyricEpic** [comment]
但是手机号总不可能都用老师的吧......




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"frank-782"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午2:11
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"叶州 普通账户"<177264839@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] [关于A营邀请码机制问题建议] (#28)



守护煮以前说的：这个因为有一些老师邀请学生注册的情况，所以不能这样限制（如果有更好的建议可以提出） 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"LyricEpic"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月15日(星期六) 下午2:05 
 收件人:&amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[a49594a/a-world-issues] [关于A营邀请码机制问题建议] (#28) 
 
 
 
 
 建议每个用户绑定手机号,每个手机号仅可绑定一个账号.这样不会出现一个用户通过刷小号来获取感染力勋章。

**Comment by YuzhenQin** [comment]
@frank-782 @a49594a 可以设置一个在邀请码邀请后一个星期内必须验证手机号

**Comment by a49594a** [comment]
后续可以通过调节感染力勋章任务的难度来解决，比如邀请的用户必须达到一定等级以上

**Comment by a49594a** [comment]
后续可以通过调节感染力勋章任务的难度来解决，比如邀请的用户必须达到一定等级以上

**Comment by a49594a** [comment]
后续可以通过调节感染力勋章任务的难度来解决，比如邀请的用户必须达到一定等级以上

**Comment by 19031** [comment]
可以实名或绑定QQ或微信等等

**Comment by Flancok** [comment]
现在已经限制8级或者绑定手机号才能使用邀请码生成器了。
