### ISSUE TITLE
2.0画笔的问题导致绘制顺序对图形的细微影响

### ISSUE THREAD

**Issue by ch-LyricEpic** [a49594a/a-world-issues#29]
符文大师任务等绘图任务经常会出现明明符合图形形状并且使用积木块没有超额的情况下未显示任务完成的情况,希望调整。

**Comment by Flancok** [comment]
这似乎不是bug，要完全重合（有一点点差异也不行）

**Comment by ch-LyricEpic** [comment]
是的 完全重合情况下依然不显示 这似乎就是个Bug.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"frank-782"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午2:15
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"叶州 普通账户"<177264839@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 2.0画笔的问题导致绘制顺序对图形的细微影响 (#29)




这似乎不是bug，要完全重合（有一点点差异也不行）

**Comment by Flancok** [comment]
如果有不止一个人做完了就不要怪题有问题![滑稽](https://user-images.githubusercontent.com/46376077/74583218-d8285c80-4fff-11ea-94f0-ee829751b0cc.png)

**Comment by ch-LyricEpic** [comment]
但是也有不止一个人认为题有问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"frank-782"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 下午2:32
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"叶州 普通账户"<177264839@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 2.0画笔的问题导致绘制顺序对图形的细微影响 (#29)




如果有不止一个人做完了就不要怪题有问题

**Comment by Flancok** [comment]
如果你觉得题有问题可以和出题人反馈
