### ISSUE TITLE
任务兑换界面中的错误

### ISSUE THREAD

**Issue by YuzhenQin** [a49594a/a-world-issues#3]
# 实际发生/预期发生
在**任务兑换**页面会出现”使用奥的灰烬提示“
# 重现步骤
1.进入***[阿儿法营](https://aerfaying.com/)***  
2.登陆**账户**  
3.进入***我的任务***页面  
4.点击***兑换***  
5.将**鼠标指针**移至***？***上，会出现 `想要推荐？买奥的灰烬`

**Comment by a49594a** [comment]
这似乎是个feature而不是bug。也许我没有正确理解你的意思，方便的话请截个图。
