### ISSUE TITLE
关于a营新增一些拓展模块的建议

### ISSUE THREAD

**Issue by zyc-666** [a49594a/a-world-issues#31]
# 建议加以下几个拓展模块：
- 1:部分擦除功能，目前擦除仅有全部擦除，建议增加部分擦除功能  
- 2:建议增加角色状态变量：显示为1,隐藏为2

**Comment by a49594a** [comment]
1、请使用canvas扩展改造你的程序实现相关功能；
2、自定义变量管理角色状态。因为scratch的指令集需要保持精简，自己能搞定的尽量不通过新增指令解决。
