### ISSUE TITLE
[建议] 后台自动保存

### ISSUE THREAD

**Issue by Steve-xmh** [a49594a/a-world-issues#32]
启动了自动保存之后发现等工程越大之后会导致保存速度缓慢，在这个期间也不能操纵页面，想建议做成后台保存的方式，这样不会等太长时间：
![image](https://user-images.githubusercontent.com/39523898/74598247-352c1d00-50a9-11ea-913c-5290af89f089.png)

**Comment by Steve-xmh** [comment]
现在自己有一个临时改法就是用油猴注入css风格将加载页面的元素关闭显示，保存的同时可以继续操作互不影响

**Comment by a49594a** [comment]
这样做非常危险，有导致保存的图片和项目文件不匹配的风险。
