### ISSUE TITLE
对增加中文字体的建议

### ISSUE THREAD

**Issue by zyc-666** [a49594a/a-world-issues#35]
## 预期行为

  **有缤纷多彩的中文字体**

## 实际行为

  **只有一种单调的中文字体**
# 建议增加更多字体

**Comment by YuzhenQin** [comment]
墙裂同意

**Comment by Flancok** [comment]
画笔中的打印是支持多种颜色的，~~canvas暂不支持，后续可能更新？~~（我火星了）

**Comment by a49594a** [comment]
canvas当然是支持多种字体和颜色的

**Comment by zyc-666** [comment]
@a49594a 我说的是在画角色画造型时的中文

**Comment by a49594a** [comment]
受不同设备操作系统和浏览器对不同字体的支持程度影响，不会在造型编辑器中增加更多字体。如果有需要，可以外部制作后导入
