### ISSUE TITLE
建议添加能存储长期不变的数据系统和与其配套的读取模块

### ISSUE THREAD

**Issue by Steve-xmh** [a49594a/a-world-issues#37]
如题，在做[Scratch输入法](https://www.aerfaying.com/Projects/373458)的时候发现读取速度缓慢（有一部分原因是因为传输的数据结构问题，但是不是这个 issue 的主题）。

![满满的字词库，点开一下卡几秒，而且覆盖量还不够](https://user-images.githubusercontent.com/39523898/74616497-0d00f480-5163-11ea-8b19-cb7f256cb42e.png)

想到词库有 **4MB** 之大，而且里面的内容基本上**长期不变**，也就是**只读**的数据。所以想建议提供一个这样的功能：

可以在某个页面设置存储这类数据，然后在工程里可以异步获取，但是是只读不可程序内直接修改的长期数据。

下面是我的实现思路：

- 也理解可能服务器的存储空间有限，限制可以在 8 - 16MB 一个数据；
- 可以通过使用特定的道具（可通过购买或奖励获取）使用来创建，创建后可随时在相应的管理页面进行数据的上传或下载；
- 在工程里有专门的模块进行异步获取，更好的话可以获取到进度（像 Canvas 一样有相对充足的 Ajax？）；
- 如果担心数据没有使用过而长期累积，可以尝试记录其距离上次工程被加载的数据读取次数，如果低于一定值则视作“遗弃数据”并将其删除。（建议可以对其用户进行通知，避免意外删除有效数据）

**Comment by a49594a** [comment]
有一个主要问题在于，数据一般会加载到链表当中，在调试时很容易出现海量数据又被打包到项目文件中上传的情况。

**Comment by YuzhenQin** [comment]
如果链表数据上传后清空链表应该就不会打包到项目文件中

**Comment by Steve-xmh** [comment]
刚刚QQ私聊的讨论方案，贴在这里供参考
![J4YK5BLPRME%T`)A1YV34@7](https://user-images.githubusercontent.com/39523898/74617883-64569300-516a-11ea-8a69-f86c804b86df.png)

**Comment by YuzhenQin** [comment]
然鹅并看不见 @Steve-xmh

**Comment by Steve-xmh** [comment]
@YuzhenQin 网络问题啦

**Comment by a49594a** [comment]
已经在string扩展中通过JSON相关指令实现
