### ISSUE TITLE
[bug]关于头像更换中的显示的bug

### ISSUE THREAD

**Issue by F-park** [a49594a/a-world-issues#46]
# 模板：

- bug

## 预期行为
![image](https://user-images.githubusercontent.com/52167622/75128846-15c46e00-5701-11ea-9776-b3a8626df8bb.png)

## 实际行为
![image](https://user-images.githubusercontent.com/52167622/75128857-24128a00-5701-11ea-81e1-c57861d3fc95.png)

## 操作步骤
第一次为预期行为，后面的都是实际行为
点开头像按钮再收回

- 建议
盲猜没有刷新图上去的代码

**Comment by Flancok** [comment]
已存在#7
