### ISSUE TITLE
[建议]分享二维码下面加一行链接

### ISSUE THREAD

**Issue by F-park** [a49594a/a-world-issues#48]
![image](https://user-images.githubusercontent.com/52167622/75130345-d863de80-5708-11ea-96d8-a1c6dd4857a2.png)

>如题

**Comment by cmryyy** [comment]
## 这个想法不错

**Comment by a49594a** [comment]
采纳

**Comment by Flancok** [comment]
![image](https://user-images.githubusercontent.com/46376077/77537296-caa4a300-6ed8-11ea-8060-6f32beccc43a.png)
已支持
