### ISSUE TITLE
bug：当我们刷新若干次浏览器，等程序加载完毕后绿旗还会显示在程序正中，而程序还在运行。

### ISSUE THREAD

**Issue by cmryyy** [a49594a/a-world-issues#49]
# 模板：

- bug：当我们刷新若干次浏览器，等程序加载完毕后绿旗还会显示在程序正中，而程序还在运行。

## 预期行为

  **正常情况下应该发生什么**：当加载完毕，点击程序正中绿旗时绿旗会消失，且程序开始加载

## 实际行为

  **实际上发生了什么**：加载完毕时，点击程序正中绿旗时绿旗还在，且程序开始加载

## 操作步骤

  **该问题是在怎样的操作行动中出现**：刷新加载若干次

## 系统（非必要）

  **列举所使用的浏览器和系统**：win10，360浏览器

- 建议

## 当前行为

  **需要进行优化的行为**：绿旗点击后消失

## 理想行为

  **更改后的行为**：当加载完毕，点击程序正中绿旗时绿旗会消失，且程序开始加载

## 其它

  **其它附属要求和建议**：无

**Comment by cmryyy** [comment]
提交者：宸某人呀呀呀

**Comment by Flancok** [comment]
已存在#8
