### ISSUE TITLE
建议扩展打印字符串模块的功能

### ISSUE THREAD

**Issue by Steve-xmh** [a49594a/a-world-issues#5]
比如颜色，大小，字体，粗细，下划线等功能
![{RZXM_4PWG7(N)0DGR8IM O](https://user-images.githubusercontent.com/39523898/74079731-3b514680-4a76-11ea-8eb9-6d5ecdb6ebb0.png)
~~我来帮忙做也行~~

**Comment by YuzhenQin** [comment]
@Steve-xmh 来自QQ  
![image](https://user-images.githubusercontent.com/59137898/74079728-35f3fc00-4a76-11ea-87f6-1eada36fdb4e.png)

**Comment by a49594a** [comment]
后续可能推出更强大的高级绘图功能，与h5 canvas绘图功能一一匹配

**Comment by a49594a** [comment]
已经通过canvas扩展指令彻底解决相关问题
