### ISSUE TITLE
[bug]两个关于留言重定向后的bug

### ISSUE THREAD

**Issue by F-park** [a49594a/a-world-issues#51]
# 模板：

- bug

## 预期行为

![GIF](https://user-images.githubusercontent.com/52167622/75253737-20265b00-581a-11ea-8f29-7e4c645bc177.gif)

url:https://aerfaying.com/Projects/335542#commentId=384077

## 实际行为

![GIF](https://user-images.githubusercontent.com/52167622/75253450-83fc5400-5819-11ea-921d-089d0a1a1820.gif)

url：https://aerfaying.com/Projects/327341#commentId=394120

## 操作步骤
见gif

- 建议
1.重定向后留言框会在上面的bug（且留下的言也在上面（属于重定向后的bug））
2.点击回复后报错（且没有显示500，404等问题）（盲猜代码bug）

**Comment by zyc-666** [comment]
我也有这种情况

**Comment by zhangyul** [comment]
已修复
