### ISSUE TITLE
[建议]为阿尔法营的 Markdown 添加 ScratchBlock 代码功能

### ISSUE THREAD

**Issue by Steve-xmh** [a49594a/a-world-issues#61]
Scratch 官方的论坛普遍使用 [ScratchBlock](https://github.com/scratchblocks/scratchblocks
) 来插入任意的，可视化的 Scratch 代码。这样有利于大家在评论里直接向对方交流代码。

实现方式：

在 Markdown 的代码块语法里加入新语言 scratchblock：
<pre>
<code>
&#96;&#96;&#96;scratchblock
在这里写入模块代码
&#96;&#96;&#96;
</code>
</pre>

**Comment by Flancok** [comment]
已经支持了 ~~（守护者的效率真快）~~

**Comment by Doushabao233** [comment]
~~神预言~~

大佬要是提交一个功能马上审核，普通人还得看运气（滑稽
