### ISSUE TITLE
[bug]可以随便查看别人的邀请

### ISSUE THREAD

**Issue by pikaqiur** [a49594a/a-world-issues#63]
## 预期行为

  **正常情况下不可查看别人邀请的人**

## 实际行为

  **只要打开查看我的邀请后把上面的ID号改成别人的就能看别人的邀请，但是看别人的邀请加载慢。**

## 操作步骤

  **点开我的物品，再点邀请码生成器，再点查看我的邀请，把上面的ID改成别人的，然后复制链接并刷新，在无痕模式下直接加载出来，在正常模式下加载比较慢**

## 系统（非必要）

  **360浏览器无痕小号窗口**

**Comment by Flancok** [comment]
是刻意可以查看他人邀请的，这样大家可以互相监督是否有刷小号/刷金币等行为
