### ISSUE TITLE
错误的头像图片显示

### ISSUE THREAD

**Issue by YuzhenQin** [a49594a/a-world-issues#7]
# 实际发生
图片显示**错误**
# 重现步骤
1.进入***设置***  
2.点击**头像**  
3.点击**基本信息**  
4.同*第二步*

**Comment by a49594a** [comment]
确实存在这个问题，谢谢反馈。会安排合适时间处理

**Comment by YuzhenQin** [comment]
有某徽章吗 @a49594a

**Comment by zhangyul** [comment]
已解决
