### ISSUE TITLE
[建议]能力图每天刷新

### ISSUE THREAD

**Issue by pikaqiur** [a49594a/a-world-issues#72]
## 当前行为

  **能力图刷新时间间隔特别长**

## 理想行为

  **每晚24：00刷新能力图**

## 其它

  **希望老师能采纳，谢谢**

**Comment by Doushabao233** [comment]
貌似12小时内就会刷新一遍的

**Comment by pikaqiur** [comment]
不是吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Doushabao233"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 下午3:20
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"皮卡丘R"<shuoshuo3414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] [建议]能力图每天刷新 (#72)





 
貌似1小时内就会刷新一遍的

**Comment by Doushabao233** [comment]
> 不是吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Doushabao233"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月5日(星期二) 下午3:20 收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 抄送:&nbsp;"皮卡丘R"<shuoshuo3414@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [a49594a/a-world-issues] [建议]能力图每天刷新 (#72) 貌似1小时内就会刷新一遍的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是真的貌似
