### ISSUE TITLE
查看作品BUG[bug]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#75]
## 预期行为

  **显示第当前页的作品。**

## 实际行为

  **点了，但无效，加载了一下又回到了第10页。**

## 操作步骤

  **翻到第10页，从11页开始后面页面无法打开。**

## 系统（非必要）

  **谷歌游览器，Win7系统**

**Comment by 19031** [comment]
有勋章吗/滑稽

**Comment by 19031** [comment]
有勋章吗:xyx

**Comment by 19031** [comment]
有勋章吗

:trollface:
--

**Comment by Flancok** [comment]
非bug，此举只为了防止爬虫浪费服务器资源，等级达到一定以后就不受限制了。
