### ISSUE TITLE
增加更多模块[建议]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#76]
## 当前行为

  **目前阿尔法营提供的拓展：Lazy Audio、Canvas、战场、字符串扩展、Javascript扩展、Community、Puzzle、Kinect**

## 理想行为

  **   增加更多模块，增加趣味。比如：今日天气（这个直接读取天气网站的数据就OK了）数据图表（就是图表比如可以创建一个表有行有列，而不是列表只有列，让数据可视化，一图胜千言）、帐号云广播（一个云广播从这个设备广播到另一个设备，实现实现同帐号或异账号作品间跨设备和跨作品的数据互联）、舞台录制（就是加一个截屏、录屏的东东）、移动端积木（比如识别手机的陀螺仪，来判断是否倾斜手机，以及手机的高度，当然要用户允许才能获取）、文字代码（将文字转换为数字或代码，并可以转换回来）、汉字拼音（根据文字代码想的，就是在库中找到这个汉字的拼音设置为一个变量给用户）、屏幕识别（检测是否全屏，我觉的没什么用，呵呵），如果可以就再搞一个智能AI比如对话机器人那种。**

## 其它

  **没什么……**

**Comment by 19031** [comment]
我是专业人员吗……

**Comment by YuzhenQin** [comment]
额

**Comment by YuzhenQin** [comment]
建议私聊守护煮，给手术煮一个带api且method是post而且返回值是json的天气网站加入白名单，然后就可以用js模块了

**Comment by YuzhenQin** [comment]
云广播貌似可以通过多线程循环加载/上传json完成（？）

**Comment by YuzhenQin** [comment]
不同作品也可以使用json

**Comment by YuzhenQin** [comment]
汉字拼音建议用steve IME

**Comment by 19031** [comment]
> 汉字拼音建议用steve IME

我都不知道是什么……

**Comment by YuzhenQin** [comment]
只能AI请自行写NLP（自然语言处理）worker（滑稽）

**Comment by 19031** [comment]
> 只能AI请自行写NLP（自然语言处理）worker（滑稽）

人家AI还有人脸识别呢:trollface:

**Comment by YuzhenQin** [comment]
自己写（滑稽x2）

**Comment by 19031** [comment]
> 自己写（滑稽x2）

我正在查你在说什么……

**Comment by YuzhenQin** [comment]
> 文字代码（将文字转换为数字或代码，并可以转换回来）  
很简单啊，用js的escape()和unescape()

**Comment by Steve-xmh** [comment]
模块太过专一，不适合作为扩展出现
