### ISSUE TITLE
谜题（打卡任务）已成功但无法领取奖励

### ISSUE THREAD

**Issue by HeZimo777** [a49594a/a-world-issues#87]
![](https://asset.mozhua.org:444/Media?name=730F0D3F697BB4BBFB74F78FAFF61FBA.png)，无法领取奖励！https://www.aerfaying.com/Puzzle/Start#13806
![image](https://user-images.githubusercontent.com/62694632/77631142-23cb1000-6f87-11ea-8109-6a27b1c554fe.png)

**Comment by Flancok** [comment]
并非bug（提示：需要用到的运算类别的积木）
