### ISSUE TITLE
积木Canvas最好能汉化[建议]

### ISSUE THREAD

**Issue by HeZimo777** [a49594a/a-world-issues#88]
要不然根本看不懂，或者在CANVAS积木的标题栏的一侧加一个“教程 ”按钮，打开后就有教程视频

**Comment by HeZimo777** [comment]
我是亡灵-子墨

**Comment by Flancok** [comment]
canvas不会汉化，另外社区内已经有许多canvas教程/作品可供参考

**Comment by HeZimo777** [comment]
好吧！



在 2020-03-26 17:43:33，"frank-782" <notifications@github.com> 写道：

canvas不会汉化，另外社区内已经有许多canvas教程/作品可供参考
