### ISSUE TITLE
笑脸BUG[bug]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#89]
## 预期行为

  **显示
![0020033001230718_b](https://user-images.githubusercontent.com/62270346/77866070-fd95c080-7263-11ea-8980-d6a1f450a27f.png)（好像有点大……）
**

## 实际行为

  **出现奸笑……**

## 操作步骤

  **打/滑稽**

## 系统（非必要）

  **这是名称标错了。**

**Comment by Flancok** [comment]
没有问题a，这个表情有滑稽的意思，大多数用户也更倾向于打滑稽而不是奸笑
