### ISSUE TITLE
挖矿任务点击“前往”后的错误

### ISSUE THREAD

**Issue by EamonKowk** [a49594a/a-world-issues#9]
![image](https://user-images.githubusercontent.com/48320775/74122172-353da000-4c05-11ea-8f5a-67b608b4d8e1.png)
在矿洞任务时点击
 ![image](https://user-images.githubusercontent.com/48320775/74122181-3e2e7180-4c05-11ea-8e33-e91ee73f798f.png)
会这样：
![image](https://user-images.githubusercontent.com/48320775/74122190-438bbc00-4c05-11ea-8c7e-f0758d555f74.png)

**Comment by ch-LyricEpic** [comment]
这不是刷新一下搞定的事情吗

**Comment by EamonKowk** [comment]
刷新没用哇，还是这样，而且头像和UI都变了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CykaBlyat"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:06
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)




这不是刷新一下搞定的事情吗

**Comment by ch-LyricEpic** [comment]
重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "EamonKowk"<notifications@github.com&gt;; 
发送时间: 2020年2月10日(星期一) 中午1:08
收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 
抄送: "叶州 普通账户"<177264839@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



刷新没用哇，还是这样，而且头像和UI都变了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"CykaBlyat"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月10日(星期一) 中午1:06 
 收件人:&amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;gt;;"Manual"<manual@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 
 这不是刷新一下搞定的事情吗

**Comment by EamonKowk** [comment]
所以这样还是没用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LyricEpic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:09
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "EamonKowk"<notifications@github.com&amp;gt;;  
 发送时间: 2020年2月10日(星期一) 中午1:08 
 收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;;  
 抄送: "叶州 普通账户"<177264839@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 刷新没用哇，还是这样，而且头像和UI都变了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"CykaBlyat"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年2月10日(星期一) 中午1:06  
  收件人:&amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)  
   
   
   
   
  这不是刷新一下搞定的事情吗

**Comment by ch-LyricEpic** [comment]
你使用Google浏览器的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "EamonKowk"<notifications@github.com&gt;; 
发送时间: 2020年2月10日(星期一) 中午1:11
收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 
抄送: "叶州 普通账户"<177264839@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



所以这样还是没用 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"LyricEpic"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月10日(星期一) 中午1:09 
 收件人:&amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;gt;;"Manual"<manual@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "EamonKowk"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年2月10日(星期一) 中午1:08  
  收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;gt;;   
  抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;gt;;   
  主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)  
   
   
   
  刷新没用哇，还是这样，而且头像和UI都变了   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"CykaBlyat"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:06   
   收件人:&amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)   
     
     
     
     
   这不是刷新一下搞定的事情吗

**Comment by EamonKowk** [comment]
chrome内核的edge




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LyricEpic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:15
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



你使用Google浏览器的吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "EamonKowk"<notifications@github.com&amp;gt;;  
 发送时间: 2020年2月10日(星期一) 中午1:11 
 收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;;  
 抄送: "叶州 普通账户"<177264839@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 所以这样还是没用  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"LyricEpic"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年2月10日(星期一) 中午1:09  
  收件人:&amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)  
   
   
   
  重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "EamonKowk"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年2月10日(星期一) 中午1:08   
   收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)   
     
     
     
   刷新没用哇，还是这样，而且头像和UI都变了    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"CykaBlyat"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:06    
    收件人:&amp;amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)    
       
       
       
       
    这不是刷新一下搞定的事情吗

**Comment by ch-luckylai** [comment]
不是的，因为前往是去到谜题的地址，而该谜题并没有被编辑开发。但是由于重定向的原因，出现在了老版的报错页面上，所以头像和报错信息不同。

**Comment by ch-LyricEpic** [comment]
建议使用全Google架构 edge有时会因架构问题出现BUG




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "EamonKowk"<notifications@github.com&gt;; 
发送时间: 2020年2月10日(星期一) 中午1:16
收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;; 
抄送: "叶州 普通账户"<177264839@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



chrome内核的edge 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"LyricEpic"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月10日(星期一) 中午1:15 
 收件人:&amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;gt;;"Manual"<manual@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 你使用Google浏览器的吗  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "EamonKowk"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年2月10日(星期一) 中午1:11  
  收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;gt;;   
  抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;gt;;   
  主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)  
   
   
   
  所以这样还是没用   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"LyricEpic"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:09   
   收件人:&amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)   
     
     
     
   重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: "EamonKowk"<notifications@github.com&amp;amp;amp;amp;gt;;     
    发送时间: 2020年2月10日(星期一) 中午1:08    
    收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;gt;;     
    抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;     
    主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)    
       
       
       
    刷新没用哇，还是这样，而且头像和UI都变了     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:&amp;amp;amp;amp;amp;nbsp;"CykaBlyat"<notifications@github.com&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:06     
     收件人:&amp;amp;amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     抄送:&amp;amp;amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)     
         
         
         
         
     这不是刷新一下搞定的事情吗

**Comment by ch-luckylai** [comment]
@LyricEpic-NanoCreate 不是你所说的那样

**Comment by EamonKowk** [comment]
那这也不能怪浏览器，网站bug得修复哇，总不能让用户换浏览器吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LyricEpic"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:18
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)



建议使用全Google架构 edge有时会因架构问题出现BUG 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "EamonKowk"<notifications@github.com&amp;gt;;  
 发送时间: 2020年2月10日(星期一) 中午1:16 
 收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;gt;;  
 抄送: "叶州 普通账户"<177264839@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9) 
 
 
 
 chrome内核的edge  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"LyricEpic"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年2月10日(星期一) 中午1:15  
  收件人:&amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)  
   
   
   
  你使用Google浏览器的吗   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "EamonKowk"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年2月10日(星期一) 中午1:11   
   收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)   
     
     
     
   所以这样还是没用    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:&amp;amp;amp;amp;nbsp;"LyricEpic"<notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:09    
    收件人:&amp;amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)    
       
       
       
    重启浏览器 确保你没有账号在其他位置登录 或者已经有挖矿的线程任务     
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: "EamonKowk"<notifications@github.com&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2020年2月10日(星期一) 中午1:08     
     收件人: "a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     抄送: "叶州 普通账户"<177264839@qq.com&amp;amp;amp;amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)     
         
         
         
     刷新没用哇，还是这样，而且头像和UI都变了      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:&amp;amp;amp;amp;amp;amp;nbsp;"CykaBlyat"<notifications@github.com&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2020年2月10日(星期一) 中午1:06      
      收件人:&amp;amp;amp;amp;amp;amp;nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      抄送:&amp;amp;amp;amp;amp;amp;nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&amp;amp;amp;amp;amp;amp;gt;;"Manual"<manual@noreply.github.com&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)      
           
           
           
           
      这不是刷新一下搞定的事情吗

**Comment by YuzhenQin** [comment]
@EamonKowk 这跟浏览器没关系的啊

**Comment by EamonKowk** [comment]
我好像回复错人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YuzhenQin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午1:28
收件人:&nbsp;"a49594a/a-world-issues"<a-world-issues@noreply.github.com&gt;;
抄送:&nbsp;"𝕰𝖆𝖒𝖔𝖓𝕶𝖔𝖜𝖐"<2740835022@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [a49594a/a-world-issues] 挖矿任务点击“前往”后的错误 (#9)




@EamonKowk 这跟浏览器没关系的啊

**Comment by a49594a** [comment]
挖掘任务详情展示页面已经更新，该问题已经不存在
