### ISSUE TITLE
路障问题（请及时查看）[bug]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#90]
## 预期行为

  **被隔离，显示隔离状态，无法运行程序。**

## 实际行为

  **我打开了路障作品（不是我的作品），并且显示了有路障道具，程序可以正常运行，创作页可以打开，但是首页路障后无法打开。这个问题发生在服务器更新了使用帮助之后。
有路障：
![image](https://user-images.githubusercontent.com/62270346/77866319-1c488700-7265-11ea-8431-245904b78665.png)
路障在，却在加载作品：
![image](https://user-images.githubusercontent.com/62270346/77866349-35e9ce80-7265-11ea-9a87-2014b364d76a.png)
可以正常运行：
![image](https://user-images.githubusercontent.com/62270346/77866365-4732db00-7265-11ea-9ac2-7ce314b3d61d.png)
[作品链接](https://www.aerfaying.com/Projects/220499)

**

## 操作步骤

  **点开即可**

## 系统（非必要）

  **谷歌游览器，Win98系统。**

**Comment by 19031** [comment]
我发现运行过一会后会
![image](https://user-images.githubusercontent.com/62270346/77866905-7a766980-7267-11ea-8753-c4d7daabbddb.png)

**Comment by YuzhenQin** [comment]
额

**Comment by YuzhenQin** [comment]
其奇挂怪

**Comment by YuzhenQin** [comment]
手术煮有40多个问题还没处理...

**Comment by 19031** [comment]
> 手术煮有40多个问题还没处理...

我了个%……

**Comment by Flancok** [comment]
这是flash的问题，和a营无关。
