### ISSUE TITLE
添加购买前缀[建议]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#92]
## 当前行为

  **只有工作室的名字才能当前缀。**

## 理想行为

  **前缀可以在我的物品购买，具体看其他。**

## 其它

  **就是指定前缀（最好字体还有个颜色~），比如：[熊孩子]（黄色）、[早起早睡]（蓝色）……（那个中括号最好带着，小括号里面的是字体颜色。）。价格便宜些，不然这种装饰不太有人买（10个金币左右就行了啦），最好可以对自己或别人使用。谢谢您倾听我的建议，希望能够加入此物品。**

**Comment by 19031** [comment]
能给我个勋章吗:trollface:

**Comment by YuzhenQin** [comment]
@19031 提交bug才有徽章哦

**Comment by YuzhenQin** [comment]
10个金币想多了吧

**Comment by YuzhenQin** [comment]
我jio的2048金币就算便宜了

**Comment by 19031** [comment]
> 我jio的2048金币就算便宜了

恩……他只是几个文字而已，又不是你画出来的。

**Comment by YuzhenQin** [comment]
不是

**Comment by YuzhenQin** [comment]
主要是

**Comment by YuzhenQin** [comment]
手术煮你又不是不懂

**Comment by 19031** [comment]
> 手术煮你又不是不懂

难道他想赚钱想疯了:trollface:

**Comment by a49594a** [comment]
前缀只是工作室成员的标识，不会用作其他目的
