### ISSUE TITLE
为阿尔法营的Markdown添加HTML代码功能[建议]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#93]
## 当前行为

  **只支持Markdown代码和ScratchBlock代码。**

## 理想行为

**在Markdown的代码块语法里加入新语言HTML：**

```
```scratchblock
在这里写入HTML代码
```（这个不要）
```

## 其它

  **希望采纳。**

**Comment by YuzhenQin** [comment]
```html
<a herf="aerfaying.com">哈哈哈</a>
```

**Comment by 19031** [comment]
> ```
> < 一个 HERF = “ aerfaying.com ” >哈哈哈</ 一 >
> ```

恩？

**Comment by a49594a** [comment]
html代码有安全性问题，暂时不会支持
