### ISSUE TITLE
关于挖矿机器人的显示问题[bug]

### ISSUE THREAD

**Issue by 19031** [a49594a/a-world-issues#94]
## 预期行为

  **正常显示图案。**

## 实际行为

  **一片绿……虽然数字还在。图片：
![image](https://user-images.githubusercontent.com/62270346/77982011-d8758080-733d-11ea-81db-0e8a491084a9.png)
**

## 操作步骤

  **打开挖矿机器人，挖一会按停止：
![image](https://user-images.githubusercontent.com/62270346/77982138-2c806500-733e-11ea-80c2-32d3188f7821.png)
等一会，点启动，就会……：
![image](https://user-images.githubusercontent.com/62270346/77982233-6baeb600-733e-11ea-899a-3fca65006861.png)
不过后面挖矿正常，原石数量也没有变。

**

## 系统（非必要）

  **谷歌游览器，Win98系统。**

**Comment by 19031** [comment]
图片貌似没有显示出来……

**Comment by 19031** [comment]
可以赐我Bug勋章吗？:trollface:

**Comment by YuzhenQin** [comment]
win98¿

**Comment by YuzhenQin** [comment]
> 图片貌似没有显示出来……

githubrawusercontent被墙了

**Comment by 19031** [comment]
> win98¿

是的呢？是不是很稀有:trollface:

**Comment by 19031** [comment]
> > 图片貌似没有显示出来……
> 
> githubrawusercontent被墙了

githubrawusercontent被墙了是什么玩意:trollface:

**Comment by YuzhenQin** [comment]
> > > 图片貌似没有显示出来……
> > 
> > 
> > githubrawusercontent被墙了
> 
> githubrawusercontent被墙了是什么玩意:trollface:

raw.githubusercontent.com
是github用来存储用户上传文件（不是项目仓库的文件，而是issue里的图片之类的）的服务地址。放在亚马逊s3上。是github 的素材服务器 (assets server), 避免跟主服务抢占负载

**Comment by 19031** [comment]
> > > > 图片貌似没有显示出来……
> > > 
> > > 
> > > githubrawusercontent被墙了
> > 
> > 
> > githubrawusercontent被墙了是什么玩意：巨魔的脸：
> 
> raw.githubusercontent.com
> 是github使用存储用户上传文件（不是项目仓库的文件，还是issueissue的图片之类的）的服务地址。放在亚马逊s3上。是github的素材服务器（资产服务器），避免跟主服务抢占负载

哦，原来如此，你图片显示了吗？

**Comment by YuzhenQin** [comment]
我没有，但是我可以开V篇N，就可以了

**Comment by YuzhenQin** [comment]
GFW搞的鬼（防火长城）

**Comment by 19031** [comment]
> GFW搞的鬼（防火长城）

哈哈哈

**Comment by YuzhenQin** [comment]
额
That's a future

**Comment by 19031** [comment]
> 额
> That's a future

为什么把他关了？

**Comment by Flancok** [comment]
这是正常的，方便看是从哪里开始挖的。
