### ISSUE TITLE
[建议]自己在别人作品下留言不能删除

### ISSUE THREAD

**Issue by Ali-Eight** [a49594a/a-world-issues#96]
## 当前行为

  **自己在别人作品下留言不能删除，导致有时候发现自己说错了不能删除很尴尬**

## 理想行为

  **自己在别人作品下留言能删除**

## 其它

  **无**

**Comment by a49594a** [comment]
可能用于销毁证据。现在发出2分钟内可以修改，所以已经可以最大程度避免该问题
