### ISSUE TITLE
[bug]评论重复bug

### ISSUE THREAD

**Issue by cmryyy** [a49594a/a-world-issues#99]
## 操作步骤

  无
## 系统（非必要）

  无

![](https://asset.mozhua.org:444/Media?name=1417213FF58C51183567C630A1E8DDA8.png)

**Comment by zhangyul** [comment]
如何操作导致的啊？

**Comment by cmryyy** [comment]
@zhangyul 就是打开评论时发现这样。而且很多地方都有这个bug

**Comment by zhangyul** [comment]
> @zhangyul就是打开评论时发现这样。而且很多地方都有这个bug

好的我会留意这个问题的，也麻烦你如果再看到此问题可以提供一下链接，方便排查，谢谢

**Comment by cmryyy** [comment]
@zhangyul 并没有链接，很多留言都有这个bug，且刷新又没有了。

**Comment by zhangyul** [comment]
> @zhangyul并没有链接，很多留言都有这个bug，且刷新又没有了。

该问题应该是由于，在点击加载更多之前，又有用户新发一条消息，将第一页的最后一条挤到了第二页的第一条导致的。

**Comment by cmryyy** [comment]
@zhangyul 老师可以给我某bug勋章吗/滑稽
